// <auto-generated />
using System;
using FEPPeopleAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FEPPeopleAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240610192230_Apply Person Specialism Referential Integrity")]
    partial class ApplyPersonSpecialismReferentialIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FEPPeopleAPI.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Forename")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PersonID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.PersonSpecialism", b =>
                {
                    b.Property<int>("PersonSpecialismID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonSpecialismID"));

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<int>("SpecialismID")
                        .HasColumnType("int");

                    b.HasKey("PersonSpecialismID");

                    b.HasIndex("PersonID");

                    b.ToTable("PersonSpecialism");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.Specialism", b =>
                {
                    b.Property<int>("SpecialismID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialismID"));

                    b.Property<bool?>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("SpecialismName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecialismID");

                    b.ToTable("Specialism");
                });

            modelBuilder.Entity("PersonSpecialismSpecialism", b =>
                {
                    b.Property<int>("PersonSpecialismID")
                        .HasColumnType("int");

                    b.Property<int>("SpecialismID")
                        .HasColumnType("int");

                    b.HasKey("PersonSpecialismID", "SpecialismID");

                    b.HasIndex("SpecialismID");

                    b.ToTable("PersonSpecialismSpecialism");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.PersonSpecialism", b =>
                {
                    b.HasOne("FEPPeopleAPI.Models.Person", "Person")
                        .WithMany("PersonSpecialism")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PersonSpecialismSpecialism", b =>
                {
                    b.HasOne("FEPPeopleAPI.Models.PersonSpecialism", null)
                        .WithMany()
                        .HasForeignKey("PersonSpecialismID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEPPeopleAPI.Models.Specialism", null)
                        .WithMany()
                        .HasForeignKey("SpecialismID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.Person", b =>
                {
                    b.Navigation("PersonSpecialism");
                });
#pragma warning restore 612, 618
        }
    }
}
