// <auto-generated />
using System;
using FEPPeopleAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FEPPeopleAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240610195004_Add more database contraints")]
    partial class Addmoredatabasecontraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FEPPeopleAPI.Models.Organisation", b =>
                {
                    b.Property<int>("OrganisationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganisationID"));

                    b.Property<string>("OrganisationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<int?>("OrganisationStatusID")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int?>("OrganisationTypeID")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.HasKey("OrganisationID");

                    b.HasIndex("OrganisationStatusID");

                    b.HasIndex("OrganisationTypeID");

                    b.ToTable("Organisation");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.OrganisationStatus", b =>
                {
                    b.Property<int>("OrganisationStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganisationStatusID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.HasKey("OrganisationStatusID");

                    b.ToTable("OrganisationStatus");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.OrganisationType", b =>
                {
                    b.Property<int>("OrganisationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganisationTypeID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.HasKey("OrganisationTypeID");

                    b.ToTable("OrganisationType");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(3);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.HasKey("PersonID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.PersonAvailability", b =>
                {
                    b.Property<int>("PersonAvailabilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonAvailabilityID"));

                    b.Property<int>("DayID")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<int>("PersonID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("PersonAvailabilityID");

                    b.HasIndex("PersonID");

                    b.ToTable("PersonAvailability");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.PersonSpecialism", b =>
                {
                    b.Property<int>("PersonSpecialismID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonSpecialismID"));

                    b.Property<int>("PersonID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("SpecialismID")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.HasKey("PersonSpecialismID");

                    b.HasIndex("PersonID");

                    b.HasIndex("SpecialismID");

                    b.ToTable("PersonSpecialism");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.Specialism", b =>
                {
                    b.Property<int>("SpecialismID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialismID"));

                    b.Property<bool?>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<string>("SpecialismName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.HasKey("SpecialismID");

                    b.ToTable("Specialism");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.Organisation", b =>
                {
                    b.HasOne("FEPPeopleAPI.Models.OrganisationStatus", "OrganisationStatus")
                        .WithMany()
                        .HasForeignKey("OrganisationStatusID");

                    b.HasOne("FEPPeopleAPI.Models.OrganisationType", "OrganisationType")
                        .WithMany()
                        .HasForeignKey("OrganisationTypeID");

                    b.Navigation("OrganisationStatus");

                    b.Navigation("OrganisationType");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.PersonAvailability", b =>
                {
                    b.HasOne("FEPPeopleAPI.Models.Person", null)
                        .WithMany("PersonAvailability")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.PersonSpecialism", b =>
                {
                    b.HasOne("FEPPeopleAPI.Models.Person", "Person")
                        .WithMany("PersonSpecialism")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEPPeopleAPI.Models.Specialism", "Specialism")
                        .WithMany()
                        .HasForeignKey("SpecialismID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Specialism");
                });

            modelBuilder.Entity("FEPPeopleAPI.Models.Person", b =>
                {
                    b.Navigation("PersonAvailability");

                    b.Navigation("PersonSpecialism");
                });
#pragma warning restore 612, 618
        }
    }
}
